# Simplified GoReleaser configuration file
builds:
  - env:
      - CGO_ENABLED=0  # Disable CGO for all builds
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

# Configuration for archives to be generated.
archives:
  - format: tar.gz  # Use tar.gz for Linux and Darwin, zip for Windows
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

# Checksum and snapshot configurations
checksum:
  name_template: 'checksums.txt'

# Simple snapshot naming
snapshot:
  name_template: "{{ .Tag }}-next"

# Changelog configuration
changelog:
  use: github-native
